### ISSUE TITLE
How did you implement the card at bottom of the screen in Pokemon page.

### ISSUE THREAD

**Issue by Louis-7** [zachgibson/react-native-touch-visualizer#5]
Actually it's not an issue, I saw there is a card at bottom of the screen after you click a item from the page (here #1 ), you use a library or implement it by your self?

**Comment by zachgibson** [comment]
I used [Animated](https://facebook.github.io/react-native/docs/animations.html#animated-api) and [PanResponder](https://facebook.github.io/react-native/docs/panresponder.html). Although now I’d use [RN Gesture Handler](https://github.com/kmagiera/react-native-gesture-handler) to get native dragging.

**Comment by Louis-7** [comment]
Thanks!
